#!/bin/bash

# Before executing this script, make sure docker compose is running. Before running
# docker compose, set CODEAGENT_API_KEY and CODEAGENT_API_BASE for each container.

# If you want to run these in parallel, set a different CODEAGENT_API_KEY for each
# container so that the tests can run in parallel without interfering with each other
# (each api key must belong to a different user). In this case, just copy and paste
# the following commands into separate terminals, instead of running this script.

docker exec codeagent-py38 pytest -s -x tests
docker exec codeagent-py39 pytest -s -x tests
docker exec codeagent-py310 pytest -s -x tests
docker exec codeagent-py311 pytest -s -x tests
docker exec codeagent-py312 pytest -s -x tests
